### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by RolfR86** [deg0nz/MMM-EnergyMonitor#1]
Hello, is it possible to change the icons from battery and solar? Greetings from germany.

**Comment by deg0nz** [comment]
Hi @RolfR86,

currently it is not possible. But as long as your target icons are font awesome icons (https://fontawesome.com), it is no problem to make this configurable. The font awesome icons are already included in MagicMirror.

If you want to use your own images/icons I need to think about that.

To what do you want to change them?

**Comment by RolfR86** [comment]
Hi. Are all icons from this side integrated and can i use them when i change this  fas fa-plug into this for example? "fal fa-industry-alt"GreetingsGesendet mit der GMX Mail AppAm 13.02.22 um 22:50 schrieb Beh
                
            
            
                
                    Von: "Beh" ***@***.***>Datum: 13. Februar 2022An: "deg0nz/MMM-EnergyMonitor" ***@***.***>Cc: "RolfR86" ***@***.***>,"Mention" ***@***.***>Betreff: Re: [deg0nz/MMM-EnergyMonitor] Icons (Issue #1)
                
                
Hi @RolfR86,
currently it is not possible. But as long as your target icons are font awesome icons (https://fontawesome.com), it is no problem to make this configurable. The font awesome icons are already included in MagicMirror.
If you want to use your own images/icons I need to think about that.
To what do you want to change them?

**Comment by deg0nz** [comment]
Yes, that should be possible. The whole icons package is included in MM, yeah. MM currently uses font awesome 5 free ([link](https://fontawesome.com/v5/cheatsheet/free/solid)).

I just need to adjust some small stuff in the code to make the CSS classes configurable via the module config.

I'll try to find time to do so in the next days and will notify you when it's done.

**Comment by RolfR86** [comment]
Thats great. Many thanks. Gesendet mit der GMX Mail AppAm 13.02.22 um 23:43 schrieb Beh
                
            
            
                
                    Von: "Beh" ***@***.***>Datum: 13. Februar 2022An: "deg0nz/MMM-EnergyMonitor" ***@***.***>Cc: "Mention" ***@***.***>,"RolfR86" ***@***.***>Betreff: Re: [deg0nz/MMM-EnergyMonitor] Icons (Issue #1)
                
                
Yes, that should be possible. The whole icons package is included in MM, yeah. MM currently uses font awesome 5 free (link).
I just need to adjust some small stuff in the code to make the CSS classes configurable via the module config.
I'll try to find time to do so in the next days and will notify you when it's done.

**Comment by deg0nz** [comment]
@RolfR86 

e5974fbc2c53975046d56178b59759d2bbfbdf7e implements this.

Just add an object like in https://github.com/deg0nz/MMM-EnergyMonitor/blob/main/MMM-EnergyMonitor.js#L25-L30 to your your config and adjust it to your needs:

```js
iconCssClasses: {
    home: "fas fa-home",
    grid: "fas fa-plug",
    energyStorage: "fas fa-battery-half",
    localPowerSource: "fas fa-solar-panel"
}
```

I'm closing this issue. If anything's wrong, feel free to open it again :)
