### ISSUE TITLE
Extra comma (,) in package.json

### ISSUE THREAD

**Issue by mickecamino** [deg0nz/MMM-EnergyMonitor#6]
Installed the module today, it wont load, error log
`SyntaxError: Error parsing /home/micke/MagicMirror/modules/MMM-EnergyMonitor/package.json: Expected double-quoted property name in JSON at position 716
`

Checked package.json:
```
package.json
 #1 Unexpected ','.
    "homepage": "https://github.com/deg0nz/MMM-EnergyMonitor#readme", // Line 29, Pos 67
```
Removed the extra comma, module loaded OK (but did not show up on screen, will look into that later

**Comment by 3DJupp** [comment]
I can confirm that error.

**Comment by deg0nz** [comment]
Thanks for the hint. Fixed with https://github.com/deg0nz/MMM-EnergyMonitor/commit/a6b7a4357d5cfaf00eec537b3c75e698ec7cc22a
